### ISSUE TITLE
[Deploy Bug]TypeError & Build error on exercise_1 preview

### ISSUE THREAD

**Issue by lei900** [lei900/daily-mind-next-frontend#21]
** 概要**
```
57:6  Warning: React Hook useEffect has missing dependencies: 'isLastQuestion' and 'questionId'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps



TypeError [ERR_INVALID_URL]: Invalid URL
--
22:49:31.160 | at new NodeError (node:internal/errors:393:5)
22:49:31.161 | at URL.onParseError (node:internal/url:565:9)
22:49:31.161 | at new URL (node:internal/url:645:5)
22:49:31.161 | at dispatchHttpRequest (file:///vercel/path0/node_modules/axios/lib/adapters/http.js:171:20)
22:49:31.161 | at new Promise (<anonymous>)
22:49:31.161 | at http (file:///vercel/path0/node_modules/axios/lib/adapters/http.js:107:10)
22:49:31.162 | at Axios.dispatchRequest (file:///vercel/path0/node_modules/axios/lib/core/dispatchRequest.js:51:10)
22:49:31.162 | at Axios.request (file:///vercel/path0/node_modules/axios/lib/core/Axios.js:142:33)
22:49:31.162 | at Axios.<computed> [as get] (file:///vercel/path0/node_modules/axios/lib/core/Axios.js:168:17)
22:49:31.162 | at Function.wrap [as get] (file:///vercel/path0/node_modules/axios/lib/helpers/bind.js:5:15) {
22:49:31.163 | input: '/exercises/1/questions',
22:49:31.163 | code: 'ERR_INVALID_URL'
22:49:31.163 | }



> Build error occurred
--
22:49:31.166 | Error: Failed to collect page data for /exercise/separate-thoughts-from-feelings/questions/[id]
22:49:31.167 | at /vercel/path0/node_modules/next/dist/build/utils.js:959:15
22:49:31.168 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
22:49:31.168 | type: 'Error'
22:49:31.168 | }
22:49:31.226 | Error: Command "npm run build" exited with 1

```

**Comment by lei900** [comment]
Fix baseUrl
